language: python
python: "3.4"

addons:
  apt:
    packages:
    - python-virtualenv
    - python3-dev
    - build-essential
    - libaio1
    - libpq-dev
    - libgeos-dev
    - unzip
    - nginx

install:
  - .travis/install_tests.sh --install-ssh

script: py.test ais

deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    branch: staging
